//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_CommandCenter p_CommandCenter;
        
        private static SteamVR_Input_ActionSet_MinimapSelector p_MinimapSelector;
        
        private static SteamVR_Input_ActionSet_MechPossession p_MechPossession;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_CommandCenter CommandCenter
        {
            get
            {
                return SteamVR_Actions.p_CommandCenter.GetCopy<SteamVR_Input_ActionSet_CommandCenter>();
            }
        }
        
        public static SteamVR_Input_ActionSet_MinimapSelector MinimapSelector
        {
            get
            {
                return SteamVR_Actions.p_MinimapSelector.GetCopy<SteamVR_Input_ActionSet_MinimapSelector>();
            }
        }
        
        public static SteamVR_Input_ActionSet_MechPossession MechPossession
        {
            get
            {
                return SteamVR_Actions.p_MechPossession.GetCopy<SteamVR_Input_ActionSet_MechPossession>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_CommandCenter = ((SteamVR_Input_ActionSet_CommandCenter)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_CommandCenter>("/actions/CommandCenter")));
            SteamVR_Actions.p_MinimapSelector = ((SteamVR_Input_ActionSet_MinimapSelector)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_MinimapSelector>("/actions/MinimapSelector")));
            SteamVR_Actions.p_MechPossession = ((SteamVR_Input_ActionSet_MechPossession)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_MechPossession>("/actions/MechPossession")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.CommandCenter,
                    SteamVR_Actions.MinimapSelector,
                    SteamVR_Actions.MechPossession};
        }
    }
}
